/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author Ankur Bywar
 */
public class BloodPressureJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BloodPressureJPanel
     */
    public BloodPressureJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBloodPressureMeasurementPanel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtEnterBp = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        btnMeasureBp = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblEnterBp = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();

        jBloodPressureMeasurementPanel.setBorder(new javax.swing.border.MatteBorder(null));
        jBloodPressureMeasurementPanel.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"infant", "120-60", ">4"},
                {"toddler", "80-140", "5-6"},
                {"preschool", "80-130", "7-10"},
                {"school", "70-110", "11-16"},
                {"adolescent", "55-105", "<16"}
            },
            new String [] {
                "Meaning", "BP", "Age"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("BP Table", jPanel2);

        btnMeasureBp.setText("Measure BP");
        btnMeasureBp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMeasureBpActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel1.setText("Blood Pressure Measurement");

        lblEnterBp.setText("Enter BP:");

        lblAge.setText("Age:");

        javax.swing.GroupLayout jBloodPressureMeasurementPanelLayout = new javax.swing.GroupLayout(jBloodPressureMeasurementPanel);
        jBloodPressureMeasurementPanel.setLayout(jBloodPressureMeasurementPanelLayout);
        jBloodPressureMeasurementPanelLayout.setHorizontalGroup(
            jBloodPressureMeasurementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBloodPressureMeasurementPanelLayout.createSequentialGroup()
                .addGroup(jBloodPressureMeasurementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jBloodPressureMeasurementPanelLayout.createSequentialGroup()
                        .addGroup(jBloodPressureMeasurementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jBloodPressureMeasurementPanelLayout.createSequentialGroup()
                                .addGap(277, 277, 277)
                                .addComponent(btnMeasureBp)
                                .addGap(66, 66, 66))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBloodPressureMeasurementPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jBloodPressureMeasurementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jBloodPressureMeasurementPanelLayout.createSequentialGroup()
                                        .addComponent(lblEnterBp)
                                        .addGap(31, 31, 31)
                                        .addComponent(txtEnterBp, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jBloodPressureMeasurementPanelLayout.createSequentialGroup()
                                        .addComponent(lblAge)
                                        .addGap(42, 42, 42)
                                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(73, 73, 73)))
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jBloodPressureMeasurementPanelLayout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addGroup(jBloodPressureMeasurementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExit)
                            .addComponent(btnReset)))
                    .addGroup(jBloodPressureMeasurementPanelLayout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel1)))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jBloodPressureMeasurementPanelLayout.setVerticalGroup(
            jBloodPressureMeasurementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBloodPressureMeasurementPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addGroup(jBloodPressureMeasurementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jBloodPressureMeasurementPanelLayout.createSequentialGroup()
                        .addGroup(jBloodPressureMeasurementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEnterBp)
                            .addComponent(txtEnterBp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jBloodPressureMeasurementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAge)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(128, 128, 128)
                        .addComponent(btnMeasureBp)
                        .addGap(18, 18, 18)
                        .addComponent(btnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExit))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBloodPressureMeasurementPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jBloodPressureMeasurementPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtEnterBp.setText(null);
        txtAge.setText(null);
        lblEnterBp.setOpaque(true);
//       if (VitalSigns.equals("BloodPressure")) {
//            normalRangeMap = vitalSignNormalRange.getNormalSystolicBPMap();
//            vitalSignValue = currentVitalSign.getSystolicBloodPressure();
//        
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnMeasureBpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMeasureBpActionPerformed
        // TODO add your handling code here:
        double  BloodPressure = Double.parseDouble(txtEnterBp.getText());
        int Age = Integer.parseInt(txtAge.getText());
        
    }//GEN-LAST:event_btnMeasureBpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnMeasureBp;
    private javax.swing.JButton btnReset;
    private javax.swing.JPanel jBloodPressureMeasurementPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblEnterBp;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEnterBp;
    // End of variables declaration//GEN-END:variables
}
