/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import System.AppDataStore;
import System.Doctor;
import System.Patient;
import System.Person;
import System.PersonDirectory;
import System.PersonType;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.LayoutManager;
import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Ankur Bywar
 */
public class Login extends javax.swing.JPanel {
    PersonDirectory personDirectory;
    AppDataStore dataStore;
    JPanel mainWorkArea;
    
    /**
     * Creates new form Login
     */

    Login(AppDataStore dataStore, JPanel mainWorkArea) {
        initComponents();
        this.dataStore = dataStore;
        this.mainWorkArea = mainWorkArea;
        // populateRoleCombo();
        setSize(600,600);
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLoginPannel = new javax.swing.JPanel();
        jTitleLabel = new javax.swing.JLabel();
        jSelectRoleLabel = new javax.swing.JLabel();
        jSelectRoleComboBox = new javax.swing.JComboBox<>();
        jUsernameLabel = new javax.swing.JLabel();
        jPasswordLabel = new javax.swing.JLabel();
        jUsernameTextField = new javax.swing.JTextField();
        jButtonRegister = new javax.swing.JButton();
        jLoginButton1 = new javax.swing.JButton();
        jPasswordTextField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(208, 228, 229));

        jLoginPannel.setLayout(new java.awt.CardLayout());

        jTitleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTitleLabel.setText("Login Page");

        jSelectRoleLabel.setText("Select role");

        jSelectRoleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Doctor", "Patient", "Nurse" }));
        jSelectRoleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSelectRoleComboBoxActionPerformed(evt);
            }
        });

        jUsernameLabel.setText("Username");

        jPasswordLabel.setText("Password");

        jUsernameTextField.setToolTipText("Enter Username");
        jUsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUsernameTextFieldActionPerformed(evt);
            }
        });

        jButtonRegister.setBackground(new java.awt.Color(0, 153, 153));
        jButtonRegister.setText("Register");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });

        jLoginButton1.setBackground(new java.awt.Color(209, 225, 116));
        jLoginButton1.setText("Login");
        jLoginButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButton1ActionPerformed(evt);
            }
        });

        jPasswordTextField.setToolTipText("");
        jPasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Welcome to clinic");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLoginPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSelectRoleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSelectRoleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(jLoginButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jTitleLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLoginPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSelectRoleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSelectRoleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLoginButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRegister)
                .addContainerGap(150, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jUsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUsernameTextFieldActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        // TODO add your handling code here:
        nextScreen(new RegisterNewUser(dataStore, mainWorkArea), "RegisterNewUser");
//       
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jLoginButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButton1ActionPerformed
        // TODO add your handling code here:
        
        
        // TODO add your handling code here:
        // JPanel selectedPanel = (JPanel) cmbRoles.getSelectedItem();
        String selectedRole = String.valueOf(jSelectRoleComboBox.getSelectedItem());

        String username = jUsernameTextField.getText();
        String password = new String(jPasswordTextField.getPassword());
        
        if (PasswordValidator.validateUsernameAndPassword(username, password, dataStore) == false) {
            JOptionPane.showMessageDialog(jLoginPannel, "Invalid username OR Password. Enter correct credentials OR register as a new user");
            return;
        }

        System.out.println(selectedRole + "  " + username + "   " + password);
        
        Person p = dataStore.getPersonDirectory().getPerson(username);

        JPanel selectedPanel = null;
        switch (PersonType.from(selectedRole)) {
            case PATIENT:
                if (!p.getPersonType().equals(PersonType.PATIENT)) {
                    JOptionPane.showMessageDialog(jLoginPannel, "Patient does not exist with the provided username and password");
                    return;  
                }
                selectedPanel = new PatientDetailsJPanel(mainWorkArea, (Patient) p, dataStore);  
                //RegisterNewUser(dataStore, mainWorkArea);
                break;
            case DOCTOR:
                if (!p.getPersonType().equals(PersonType.DOCTOR)) {
                    JOptionPane.showMessageDialog(jLoginPannel, "Doctor does not exist with the provided username and password");
                    return;  
                }
                selectedPanel = new DoctorWorkAreaJPanel(mainWorkArea, (Doctor) p, dataStore);
                // RegisterNewUser(dataStore, mainWorkArea);
                break;
            default:
                    JOptionPane.showMessageDialog(jLoginPannel, "Invalid person role selected");
                    return;  
        }
        
        nextScreen(selectedPanel, "workarea");
    }//GEN-LAST:event_jLoginButton1ActionPerformed

    private void jSelectRoleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSelectRoleComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSelectRoleComboBoxActionPerformed

    private void jPasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordTextFieldActionPerformed

//    private void nextScreen(JPanel nextScreen, String screenName) {
//        mainWorkArea.removeAll();
//        mainWorkArea.add(screenName , nextScreen);
//        CardLayout layout = (CardLayout)mainWorkArea.getLayout();
//        layout.next(mainWorkArea); 
//    }
    
    private void nextScreen(JPanel nextScreen, String screenName) {
        mainWorkArea.removeAll();
        mainWorkArea.add(nextScreen, screenName);
        CardLayout layout = (CardLayout)mainWorkArea.getLayout();
        layout.next(mainWorkArea);
        
        JFrame mainFrame = new JFrame();
        mainFrame.setLayout(new BorderLayout());
        mainFrame.add(mainWorkArea, BorderLayout.CENTER);
        mainFrame.pack();
        mainFrame.setVisible(true);
        mainFrame.setResizable(false);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jLoginButton1;
    private javax.swing.JPanel jLoginPannel;
    private javax.swing.JLabel jPasswordLabel;
    private javax.swing.JPasswordField jPasswordTextField;
    private javax.swing.JComboBox<String> jSelectRoleComboBox;
    private javax.swing.JLabel jSelectRoleLabel;
    private javax.swing.JLabel jTitleLabel;
    private javax.swing.JLabel jUsernameLabel;
    private javax.swing.JTextField jUsernameTextField;
    // End of variables declaration//GEN-END:variables

}
