/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import System.AppDataStore;
import System.Doctor;
import System.House;
import System.Nurse;
import System.Patient;
import System.Person;

import System.PersonDirectory;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.time.Instant;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Ankur Bywar
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    PersonDirectory personDirectory;
    AppDataStore dataStore;
    
    static JFrame mainFrame = new JFrame();
    
    
    public MainJFrame() {
        initComponents();
        dataStore = new AppDataStore();
        personDirectory = new PersonDirectory();
        
        //setSize(1200,1200);
        //mainWorkArea.
        setResizable(true);
       
        // Create temporary patient and nurse
        Person p1 = new Patient("patient1", "patient1", "Patient1", "2132921728", Date.from(Instant.now()), 
                new House("Community1", "98109", "Seattle", "WA", "USA"), null);
        dataStore.getPersonDirectory().addPerson(p1);
        
        Person p2 = new Patient("patient2", "patient2", "Patient2", "2132921728", Date.from(Instant.now()), 
                new House("Community2", "981111", "Boston", "MA", "USA"), null);
        dataStore.getPersonDirectory().addPerson(p2);
        
        Person p3 = new Doctor("doctor1", "doctor1", "Doctor1", "2132921728", Date.from(Instant.now()), 
                new House("Community3", "981113", "Boston", "MA", "USA"), null);
        dataStore.getPersonDirectory().addPerson(p3);
        
        Person p4 = new Doctor("doctor2", "doctor2", "Doctor2", "2132921728", Date.from(Instant.now()), 
                new House("Community3", "981113", "Boston", "MA", "USA"), null);
        dataStore.getPersonDirectory().addPerson(p4);
        
        nextScreen(new Login(dataStore, mainWorkArea), "Login");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainWorkArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainWorkArea.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainWorkArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainWorkArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    private void nextScreen(JPanel nextScreen, String screenName) {
//        mainWorkArea.removeAll();
        mainWorkArea.add(nextScreen, screenName);
//        CardLayout layout = (CardLayout)mainWorkArea.getLayout();
//        layout.next(mainWorkArea);
        
        MainJFrame.mainFrame.removeAll();
        MainJFrame.mainFrame.setLayout(new BorderLayout());
        MainJFrame.mainFrame.add(mainWorkArea, BorderLayout.CENTER);
        MainJFrame.mainFrame.pack();
        MainJFrame.mainFrame.setVisible(true);
        MainJFrame.mainFrame.setResizable(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainWorkArea;
    // End of variables declaration//GEN-END:variables
}
