/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import System.AppDataStore;
import System.Appointment;
import System.Encounter;
import System.EncounterHistory;
import System.House;
import System.Patient;
import System.Person;
import System.VitalSigns;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ankur Bywar
 */
public class PatientDetailsJPanel extends javax.swing.JPanel {
    AppDataStore dataStore;
    JPanel mainWorkArea;
    Patient patient;
    /**
     * Creates new form PatientDetailNewJPanel
     */
    public PatientDetailsJPanel(JPanel mainWorkArea, Patient patient, AppDataStore dataStore) {
        initComponents();
        this.dataStore = dataStore;
        this.mainWorkArea = mainWorkArea;
        this.patient = patient;
         displayPersonDetail();
         populateUpcomingAppoimentsTable();
         pupolateEncounterHistory();
    }

   

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPatientDetailPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUpcomingAppointments = new javax.swing.JTable();
        lblTittle = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblProfilePic = new javax.swing.JLabel();
        imgLogo = new javax.swing.JLabel();
        lblPatientDetails = new javax.swing.JLabel();
        btnClickToBookAppointment = new javax.swing.JButton();
        lblNamePlaceHolder = new javax.swing.JLabel();
        lblDob1 = new javax.swing.JLabel();
        lblDobPlaceHolder = new javax.swing.JLabel();
        lblPhoneNumberPlaceHolder = new javax.swing.JLabel();
        lblAddressPlaceHolder = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblEncounterHistory = new javax.swing.JTable();

        tblUpcomingAppointments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cheif Complaint", "Doctor", "Date"
            }
        ));
        jScrollPane1.setViewportView(tblUpcomingAppointments);

        lblTittle.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblTittle.setForeground(new java.awt.Color(255, 51, 102));
        lblTittle.setText("                Welcome to Clinic");

        lblAddress.setText("Address:");

        jLabel1.setText("Upcoming Appointments");

        lblPhoneNumber.setText("Phone Number:");

        lblName.setText("Name:");

        lblProfilePic.setText("Profile Pic:");

        imgLogo.setText("<<No Image>>");

        lblPatientDetails.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblPatientDetails.setText("                           Patient Details");

        btnClickToBookAppointment.setText("Book New Appointment");
        btnClickToBookAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClickToBookAppointmentActionPerformed(evt);
            }
        });

        lblNamePlaceHolder.setText("NamePlaceHolder");

        lblDob1.setText("Dob:");

        lblDobPlaceHolder.setText("DobPlaceHolder");

        lblPhoneNumberPlaceHolder.setText("Phone Number Place Holder");

        lblAddressPlaceHolder.setText("AddressPlaceHolder");

        jLabel2.setText("Encounter History");

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        tblEncounterHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Doctor Name", "Encounter Date", "Chief Complain", "Weight", "Blood Pressure", "Respiratory Rate", "Heart Rate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblEncounterHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEncounterHistoryMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tblEncounterHistoryMouseExited(evt);
            }
        });
        jScrollPane3.setViewportView(tblEncounterHistory);

        javax.swing.GroupLayout jPatientDetailPanelLayout = new javax.swing.GroupLayout(jPatientDetailPanel);
        jPatientDetailPanel.setLayout(jPatientDetailPanelLayout);
        jPatientDetailPanelLayout.setHorizontalGroup(
            jPatientDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPatientDetailPanelLayout.createSequentialGroup()
                .addGroup(jPatientDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPatientDetailPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblProfilePic)
                        .addGap(74, 74, 74)
                        .addGroup(jPatientDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPatientDetailPanelLayout.createSequentialGroup()
                                .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPatientDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPatientDetailPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblPatientDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPatientDetailPanelLayout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(jPatientDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPatientDetailPanelLayout.createSequentialGroup()
                                                .addComponent(lblDob1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblDobPlaceHolder))
                                            .addGroup(jPatientDetailPanelLayout.createSequentialGroup()
                                                .addComponent(lblName)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblNamePlaceHolder)
                                                .addGap(137, 137, 137)
                                                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPatientDetailPanelLayout.createSequentialGroup()
                                                .addComponent(lblPhoneNumber)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblPhoneNumberPlaceHolder))
                                            .addGroup(jPatientDetailPanelLayout.createSequentialGroup()
                                                .addComponent(lblAddress)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblAddressPlaceHolder))))))
                            .addGroup(jPatientDetailPanelLayout.createSequentialGroup()
                                .addGap(205, 205, 205)
                                .addComponent(lblTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPatientDetailPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPatientDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPatientDetailPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnClickToBookAppointment))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(851, Short.MAX_VALUE))
        );
        jPatientDetailPanelLayout.setVerticalGroup(
            jPatientDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPatientDetailPanelLayout.createSequentialGroup()
                .addGroup(jPatientDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPatientDetailPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPatientDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPatientDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName)
                            .addComponent(lblNamePlaceHolder)
                            .addComponent(btnLogout))
                        .addGap(8, 8, 8)
                        .addGroup(jPatientDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDob1)
                            .addComponent(lblDobPlaceHolder))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPatientDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhoneNumber)
                            .addComponent(lblPhoneNumberPlaceHolder))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPatientDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAddress)
                            .addComponent(lblAddressPlaceHolder)))
                    .addGroup(jPatientDetailPanelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPatientDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProfilePic))))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPatientDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPatientDetailPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPatientDetailPanelLayout.createSequentialGroup()
                        .addComponent(btnClickToBookAppointment)
                        .addGap(41, 41, 41)))
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(552, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1788, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(jPatientDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1160, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPatientDetailPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnClickToBookAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClickToBookAppointmentActionPerformed
        // TODO add your handling code here:
        PatientAppointmentBookingPanel pwa = new PatientAppointmentBookingPanel (mainWorkArea, dataStore, patient);
        mainWorkArea.add("SPatientWorkAreaJPanel ", pwa);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.next(mainWorkArea);
    }//GEN-LAST:event_btnClickToBookAppointmentActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        nextScreen(new Login(dataStore, mainWorkArea), "Login");
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void tblEncounterHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEncounterHistoryMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblEncounterHistoryMouseClicked

    private void tblEncounterHistoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEncounterHistoryMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tblEncounterHistoryMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClickToBookAppointment;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPatientDetailPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAddressPlaceHolder;
    private javax.swing.JLabel lblDob1;
    private javax.swing.JLabel lblDobPlaceHolder;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNamePlaceHolder;
    private javax.swing.JLabel lblPatientDetails;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPhoneNumberPlaceHolder;
    private javax.swing.JLabel lblProfilePic;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JTable tblEncounterHistory;
    private javax.swing.JTable tblUpcomingAppointments;
    // End of variables declaration//GEN-END:variables

    private void displayPersonDetail() {
        lblNamePlaceHolder.setText(patient.getName());
        lblDobPlaceHolder.setText(patient.getDob().toString());
        House house = patient.getHouse();
        lblAddressPlaceHolder.setText(house.getCommunity() + ", " 
                + house.getCity() + ", " 
                + house.getState() + ", "
                + house.getZipcode() + ", "
                + house.getCountry());
        lblPhoneNumberPlaceHolder.setText(patient.getPhoneNumber());
        if (patient.getLogoImage() != null) {
            imgLogo.setIcon(patient.getLogoImage());
        } else {
            imgLogo.setText("No Logo");
        }
    }

    private void populateUpcomingAppoimentsTable() {
        DefaultTableModel  model = (DefaultTableModel) tblUpcomingAppointments.getModel();
        List<Appointment> apts = dataStore.getAppointment(patient.getUsername());
        model.setRowCount(0);
        if (apts == null) {
             return;
        }
        for (Appointment apt : apts) {
            Object row[] = new Object[3];
            row[0] = apt.getCheifComplain();
            row[1] = apt.getDoctor().getName();
            row[2] = apt.getDate();
            model.addRow(row);
        }
    }
    
    private void nextScreen(JPanel nextScreen, String screenName) {
        mainWorkArea.removeAll();
        mainWorkArea.add(screenName , nextScreen);
        CardLayout layout = (CardLayout)mainWorkArea.getLayout();
        layout.next(mainWorkArea); 
        
    }

    private void pupolateEncounterHistory() {
        List<Appointment> appointments = dataStore.getEncounterHistory(patient.getUsername());
        if (appointments == null || appointments.isEmpty()) {
            return;
        }
        
        DefaultTableModel  model = (DefaultTableModel) tblEncounterHistory.getModel();
        model.setRowCount(0);
        for (Appointment apt : appointments) {
            Object row[] = new Object[7];
            row[0] = apt.getDoctor().getName();
            row[1] = apt.getDate().toString();
            row[2] = apt.getCheifComplain();
            row[3] = apt.getVitalSign().getWeight();
            row[4] = apt.getVitalSign().getBloodPressure().getLow() + "-" + apt.getVitalSign().getBloodPressure().getHigh();
            row[5] = apt.getVitalSign().getRespiratoryRate();
            row[6] = apt.getVitalSign().getHeartRate();
            model.addRow(row);
        }
        
    }
    
}
