/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import System.AppDataStore;
import System.Appointment;
import System.Doctor;
import System.EncounterHistory;
import System.House;
import System.Nurse;
import System.Patient;
import System.Person;
import System.Range;
import System.VitalSignHistory;
import System.VitalSigns;
import java.awt.CardLayout;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ankur Bywar
 */
public class PatientVitalSignCollectionJPanel extends javax.swing.JPanel {
    JPanel mainWorkArea;
    Doctor doctor;
    Patient patient;
    AppDataStore dataStore;
    Appointment appointment;

   // VitalSigns vitalSign;
    /**
     * Creates new form NUrseWorkAJPanel
     */
    public PatientVitalSignCollectionJPanel(JPanel mainWorkArea, Doctor doctor, Patient patient, AppDataStore dataStore, Appointment appointment) {
        initComponents();
        this.mainWorkArea = mainWorkArea;
        this.dataStore = dataStore;
         this.doctor = doctor;
         this.patient = patient;
         this.appointment = appointment;
         displayPersonDetail();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNurseAreaWorkPanel = new javax.swing.JPanel();
        txtWeight = new javax.swing.JTextField();
        lblBloodPressure = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnSaveVitalSigns = new javax.swing.JButton();
        lblTittle = new javax.swing.JLabel();
        txtLowBp = new javax.swing.JTextField();
        lblRespRate = new javax.swing.JLabel();
        lblHeartRate = new javax.swing.JLabel();
        txtRespirtoryRate = new javax.swing.JTextField();
        txtHeartRate = new javax.swing.JTextField();
        lblPatientNamePlaceholder = new javax.swing.JLabel();
        lblDoctorNamePlaceholder = new javax.swing.JLabel();
        lblWeight1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        txtHighBp = new javax.swing.JTextField();
        lblWeight2 = new javax.swing.JLabel();

        lblBloodPressure.setText("Blood Pressure:");

        lblWeight.setText("Weight:");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSaveVitalSigns.setText("Save");
        btnSaveVitalSigns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveVitalSignsActionPerformed(evt);
            }
        });

        lblTittle.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblTittle.setForeground(new java.awt.Color(255, 51, 102));
        lblTittle.setText("Vital signs collection");

        txtLowBp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLowBpActionPerformed(evt);
            }
        });

        lblRespRate.setText("Respiratory Rate:");

        lblHeartRate.setText("Heart Rate:");

        lblPatientNamePlaceholder.setText("Patient: <patient_placeholder>");

        lblDoctorNamePlaceholder.setText("Doctor: <doctor_placeholder>");

        lblWeight1.setText("kgs");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"infant", "120-60", ">4"},
                {"toddler", "80-140", "5-6"},
                {"preschool", "80-130", "7-10"},
                {"school", "70-110", "11-16"},
                {"adolescent", "55-105", "<16"}
            },
            new String [] {
                "Meaning", "BP", "Age"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"infant", "120-60", ">4"},
                {"toddler", "80-140", "5-6"},
                {"preschool", "80-130", "7-10"},
                {"school", "70-110", "11-16"},
                {"adolescent", "55-105", "<16"}
            },
            new String [] {
                "Meaning", "BP", "Age"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"infant", "120-60", ">4"},
                {"toddler", "80-140", "5-6"},
                {"preschool", "80-130", "7-10"},
                {"school", "70-110", "11-16"},
                {"adolescent", "55-105", "<16"}
            },
            new String [] {
                "Meaning", "BP", "Age"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"infant", "120-60", ">4"},
                {"toddler", "80-140", "5-6"},
                {"preschool", "80-130", "7-10"},
                {"school", "70-110", "11-16"},
                {"adolescent", "55-105", "<16"}
            },
            new String [] {
                "Meaning", "BP", "Age"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable5);

        txtHighBp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHighBpActionPerformed(evt);
            }
        });

        lblWeight2.setText("-");

        javax.swing.GroupLayout jNurseAreaWorkPanelLayout = new javax.swing.GroupLayout(jNurseAreaWorkPanel);
        jNurseAreaWorkPanel.setLayout(jNurseAreaWorkPanelLayout);
        jNurseAreaWorkPanelLayout.setHorizontalGroup(
            jNurseAreaWorkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jNurseAreaWorkPanelLayout.createSequentialGroup()
                .addGroup(jNurseAreaWorkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jNurseAreaWorkPanelLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(jNurseAreaWorkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWeight)
                            .addComponent(lblRespRate)
                            .addComponent(lblHeartRate)
                            .addComponent(lblPatientNamePlaceholder)
                            .addComponent(lblDoctorNamePlaceholder)
                            .addComponent(lblBloodPressure))
                        .addGap(23, 23, 23)
                        .addGroup(jNurseAreaWorkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jNurseAreaWorkPanelLayout.createSequentialGroup()
                                .addComponent(txtLowBp, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblWeight2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHighBp, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jNurseAreaWorkPanelLayout.createSequentialGroup()
                                .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblWeight1))
                            .addComponent(txtRespirtoryRate, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jNurseAreaWorkPanelLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnBack))
                    .addGroup(jNurseAreaWorkPanelLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(lblTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jNurseAreaWorkPanelLayout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(btnSaveVitalSigns))
                    .addGroup(jNurseAreaWorkPanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jNurseAreaWorkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(1060, Short.MAX_VALUE))
            .addGroup(jNurseAreaWorkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jNurseAreaWorkPanelLayout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1288, Short.MAX_VALUE)))
        );
        jNurseAreaWorkPanelLayout.setVerticalGroup(
            jNurseAreaWorkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jNurseAreaWorkPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jNurseAreaWorkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jNurseAreaWorkPanelLayout.createSequentialGroup()
                        .addComponent(lblTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPatientNamePlaceholder)
                        .addGap(8, 8, 8)
                        .addComponent(lblDoctorNamePlaceholder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jNurseAreaWorkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblWeight)
                            .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWeight1))
                        .addGroup(jNurseAreaWorkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBloodPressure)
                            .addComponent(txtLowBp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHighBp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWeight2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jNurseAreaWorkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRespRate)
                            .addComponent(txtRespirtoryRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jNurseAreaWorkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHeartRate)
                            .addComponent(txtHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(btnSaveVitalSigns)
                .addContainerGap(318, Short.MAX_VALUE))
            .addGroup(jNurseAreaWorkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jNurseAreaWorkPanelLayout.createSequentialGroup()
                    .addContainerGap(455, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(372, 372, 372)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jNurseAreaWorkPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jNurseAreaWorkPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveVitalSignsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveVitalSignsActionPerformed
        // TODO add your handling code here:
        
        String weight = txtWeight.getText();
        if (weight == null || weight.isEmpty()) {
            JOptionPane.showMessageDialog(jNurseAreaWorkPanel, "Weight cannot be empty");
            return;  
        }
        
        String lowBp = txtLowBp.getText();
        if (lowBp == null || lowBp.isEmpty()) {
            JOptionPane.showMessageDialog(jNurseAreaWorkPanel, "BP field cannot be empty");
            return;  
        }
        
        String highBp = txtHighBp.getText();
        if (highBp == null || highBp.isEmpty()) {
            JOptionPane.showMessageDialog(jNurseAreaWorkPanel, "BP field cannot be empty");
            return;  
        }
        
        String hr = txtHeartRate.getText();
        if (hr == null || hr.isEmpty()) {
            JOptionPane.showMessageDialog(jNurseAreaWorkPanel, "Heart Rate cannot be empty");
            return;  
        }        
        
        String rr = txtRespirtoryRate.getText();
        if (rr == null || rr.isEmpty()) {
            JOptionPane.showMessageDialog(jNurseAreaWorkPanel, "Respiratory Rate cannot be empty");
            return;  
        }
        
        VitalSigns vs = new VitalSigns();
        
        try {
            vs.setWeight(Integer.valueOf(weight));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(jNurseAreaWorkPanel, "Invalid weight. Should be numeric");
            return;   
        }
        
        try {
            vs.setBloodPressure(new Range(Double.valueOf(lowBp), Double.valueOf(highBp)));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(jNurseAreaWorkPanel, "Invalid blood pressure. Should be numeric");
            return;  
        }
    
        try {
            vs.setHeartRate(Integer.valueOf(hr));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(jNurseAreaWorkPanel, "Invalid heart rate. Should be numeric");
            return;   
        }
        
        try {
            vs.setRespiratoryRate(Integer.valueOf(rr));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(jNurseAreaWorkPanel, "Invalid respiratory rate. Should be numeric");
            return;  
        }
        
        patient.setCurrentVitalSigns(vs);
        patient.getEncounterHistory().add(vs);
        appointment.setVitalsSign(vs);
        
        List<Appointment> appointments = dataStore.getAppointment(patient.getUsername());
        appointments.remove(appointment);
        dataStore.addToEncounterHistory(patient.getUsername(), appointment);
        
        
        JOptionPane.showMessageDialog(jNurseAreaWorkPanel, "Vital signs saved"); 
    }//GEN-LAST:event_btnSaveVitalSignsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        nextScreen(new DoctorWorkAreaJPanel(mainWorkArea, doctor, dataStore));
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtLowBpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLowBpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLowBpActionPerformed

    private void txtHighBpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHighBpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHighBpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSaveVitalSigns;
    private javax.swing.JPanel jNurseAreaWorkPanel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JLabel lblBloodPressure;
    private javax.swing.JLabel lblDoctorNamePlaceholder;
    private javax.swing.JLabel lblHeartRate;
    private javax.swing.JLabel lblPatientNamePlaceholder;
    private javax.swing.JLabel lblRespRate;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JLabel lblWeight1;
    private javax.swing.JLabel lblWeight2;
    private javax.swing.JTextField txtHeartRate;
    private javax.swing.JTextField txtHighBp;
    private javax.swing.JTextField txtLowBp;
    private javax.swing.JTextField txtRespirtoryRate;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables

    private void displayPersonDetail() {
        lblDoctorNamePlaceholder.setText("Doctor: " + doctor.getName());
        lblPatientNamePlaceholder.setText("Patient: " + patient.getName());
    }
    
    
    private void nextScreen(JPanel nextScreen) {
        mainWorkArea.removeAll();
        mainWorkArea.add("RegisterNewUser" , nextScreen);
        CardLayout layout = (CardLayout)mainWorkArea.getLayout();
        layout.next(mainWorkArea); 
    }
   
}

