/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import System.AppDataStore;
import System.Appointment;
import System.Doctor;
import System.EncounterHistory;
import System.House;
import System.Nurse;
import System.Patient;
import System.Person;
import System.PersonDirectory;
import java.awt.CardLayout;
import java.util.Date;
import java.util.List;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ankur Bywar
 */
public class PatientAppointmentBookingPanel extends javax.swing.JPanel {
    AppDataStore dataStore;
    Patient patient;
    JPanel mainWorkArea;
    EncounterHistory history;
    Person person;
    
    
    List<Person> doctors;
    
    /**
     * Creates new form PatientWorkJPanel
     */
    public PatientAppointmentBookingPanel(JPanel mainWorkArea ,AppDataStore dataStore,  Patient patient  ) {
        initComponents();
        this.mainWorkArea = mainWorkArea;
        this.dataStore = dataStore;
        this.patient = patient;
        this.person =person;
        setSize(1000,800);

        doctors = dataStore.getPersonDirectory().getDoctors();
        if (!doctors.isEmpty()) {
            for (Person doctor : doctors) {
               jComboBoxDoctorList.addItem(doctor.getName()); 
            }
        }
    


    }

//    PatientAppointmentBookingPanel(JPanel mainWorkArea, Patient patient) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }

//    PatientAppointmentBookingPanel(JPanel mainWorkArea, Patient patient) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }

  

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPatientWorkAreaJPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtChiefComplain = new javax.swing.JTextField();
        lblAppointmentDate = new javax.swing.JLabel();
        lblTittle = new javax.swing.JLabel();
        lblPatientWorkArea = new javax.swing.JLabel();
        lblAppointmentBook = new javax.swing.JLabel();
        lblDoctorTxt = new javax.swing.JLabel();
        btnBookAppointment = new javax.swing.JButton();
        lblChiefComplain = new javax.swing.JLabel();
        txtAppointmentDateChooser = new com.toedter.calendar.JDateChooser();
        btnBack = new javax.swing.JButton();
        jComboBoxDoctorList = new javax.swing.JComboBox<>();

        lblAppointmentDate.setText("Date:");

        lblTittle.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblTittle.setForeground(new java.awt.Color(255, 51, 102));
        lblTittle.setText("                    Welcome to Clinic!!!!!!!!!");

        lblPatientWorkArea.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblPatientWorkArea.setText("Patient Work Area Panel");

        lblAppointmentBook.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        lblAppointmentBook.setText("Book an Appointment");

        lblDoctorTxt.setText("Doctor:");

        btnBookAppointment.setBackground(new java.awt.Color(51, 51, 255));
        btnBookAppointment.setText("Book Appointment");
        btnBookAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookAppointmentActionPerformed(evt);
            }
        });

        lblChiefComplain.setText("Cheif Complain:");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jComboBoxDoctorList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDoctorListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnBack)
                        .addGap(137, 137, 137)
                        .addComponent(lblTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(lblAppointmentBook)))
                .addGap(0, 445, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDoctorTxt)
                            .addComponent(lblAppointmentDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAppointmentDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxDoctorList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblChiefComplain)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtChiefComplain, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblPatientWorkArea)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btnBookAppointment)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addGap(18, 18, 18)
                .addComponent(lblPatientWorkArea)
                .addGap(32, 32, 32)
                .addComponent(lblAppointmentBook, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoctorTxt)
                    .addComponent(jComboBoxDoctorList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAppointmentDate)
                    .addComponent(txtAppointmentDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblChiefComplain)
                    .addComponent(txtChiefComplain, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btnBookAppointment)
                .addContainerGap(501, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPatientWorkAreaJPanelLayout = new javax.swing.GroupLayout(jPatientWorkAreaJPanel);
        jPatientWorkAreaJPanel.setLayout(jPatientWorkAreaJPanelLayout);
        jPatientWorkAreaJPanelLayout.setHorizontalGroup(
            jPatientWorkAreaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPatientWorkAreaJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPatientWorkAreaJPanelLayout.setVerticalGroup(
            jPatientWorkAreaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPatientWorkAreaJPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPatientWorkAreaJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPatientWorkAreaJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookAppointmentActionPerformed
        // TODO add your handling code here:

        Date appointmentDate = txtAppointmentDateChooser.getDate();
        if (appointmentDate.before(new Date(1920, 01, 01))) {

        }
        
        String CheifComplain= txtChiefComplain.getText();
        
        String doctorName = String.valueOf(jComboBoxDoctorList.getSelectedItem());
        Person doctor = null;
        for (Person doc : doctors) {
            if (doc.getName().equals(doctorName)) {
                doctor = doc;
            }
        }
      
        Appointment appt = new Appointment(patient, CheifComplain, doctor, appointmentDate);
        dataStore.addAppointment(patient.getUsername(), appt);
        
         System.out.println("Date: " + appointmentDate.toString());
      
        JOptionPane.showMessageDialog(this,"appointment booked");

//        PatientDetailsJPanel pdjp = new PatientDetailsJPanel(mainWorkArea, patient);
//        loginPannel.add("PatientDetailsJPanel", pdjp);
//        CardLayout layout = (CardLayout) loginPannel.getLayout();
//        layout.next(loginPannel);
//        
    }//GEN-LAST:event_btnBookAppointmentActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        nextScreen(new PatientDetailsJPanel(mainWorkArea, patient, dataStore), "PatientDetailsJPanel");
    }//GEN-LAST:event_btnBackActionPerformed

    private void jComboBoxDoctorListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDoctorListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDoctorListActionPerformed

    private void nextScreen(JPanel nextScreen, String screenName) {
        mainWorkArea.removeAll();
        mainWorkArea.add(screenName , nextScreen);
        CardLayout layout = (CardLayout)mainWorkArea.getLayout();
        layout.next(mainWorkArea); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBookAppointment;
    private javax.swing.JComboBox<String> jComboBoxDoctorList;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPatientWorkAreaJPanel;
    private javax.swing.JLabel lblAppointmentBook;
    private javax.swing.JLabel lblAppointmentDate;
    private javax.swing.JLabel lblChiefComplain;
    private javax.swing.JLabel lblDoctorTxt;
    private javax.swing.JLabel lblPatientWorkArea;
    private javax.swing.JLabel lblTittle;
    private com.toedter.calendar.JDateChooser txtAppointmentDateChooser;
    private javax.swing.JTextField txtChiefComplain;
    // End of variables declaration//GEN-END:variables
}
